// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMVQwo2geCnslAh_zHCVDqBb4xZbrtc0o',
    appId: '1:160561747258:web:13128847392fba96adac03',
    messagingSenderId: '160561747258',
    projectId: 'currency-converter-7679d',
    authDomain: 'currency-converter-7679d.firebaseapp.com',
    storageBucket: 'currency-converter-7679d.appspot.com',
    measurementId: 'G-QGZFTJXQVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7AJmD27cjKc68XZ0JlRnurylgUwZx1gE',
    appId: '1:160561747258:android:bd16f425713e9d9eadac03',
    messagingSenderId: '160561747258',
    projectId: 'currency-converter-7679d',
    storageBucket: 'currency-converter-7679d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8_MjSvp8Xpg1RW2-4GtOZUjuyuZA9I5c',
    appId: '1:160561747258:ios:77e88d2961e1fe59adac03',
    messagingSenderId: '160561747258',
    projectId: 'currency-converter-7679d',
    storageBucket: 'currency-converter-7679d.appspot.com',
    iosBundleId: 'com.example.currencyConverter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8_MjSvp8Xpg1RW2-4GtOZUjuyuZA9I5c',
    appId: '1:160561747258:ios:77e88d2961e1fe59adac03',
    messagingSenderId: '160561747258',
    projectId: 'currency-converter-7679d',
    storageBucket: 'currency-converter-7679d.appspot.com',
    iosBundleId: 'com.example.currencyConverter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMVQwo2geCnslAh_zHCVDqBb4xZbrtc0o',
    appId: '1:160561747258:web:4979cd4d3c7fe8dbadac03',
    messagingSenderId: '160561747258',
    projectId: 'currency-converter-7679d',
    authDomain: 'currency-converter-7679d.firebaseapp.com',
    storageBucket: 'currency-converter-7679d.appspot.com',
    measurementId: 'G-DBF58WGHZL',
  );
}
